packages:
  - '.'
allowBuilds:
  esbuild: set this to true or false
overrides:
  fast-xml-parser@5.2.5: ^5.7.0
  undici@5.29.0: ^6.24.0
  minimatch@3.1.2: ^3.1.4
  brace-expansion@1.1.12: ^1.1.13
  uuid@8.3.2: ^11.1.1
